# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install requirements 
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update           
          sudo apt-get build-dep linux-image-4.8.0-51-generic 
          sudo apt-get build-dep mame vice xserver-xorg-video-nouveau 
          sudo apt-get install fakeroot qt5-default qtbase5-dev qtbase5-dev-tools git unrar libxml2-dev libsdl1.2-dev cmake libarchive13 libavcodec57 libavformat57 libavutil55 libc6 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgl1-mesa-glx libjpeg8 libopenal1 libsfml-graphics2.4 libsfml-network2.4 libsfml-system2.4 libsfml-window2.4 libstdc++6 libswresample2 libswscale4 libx11-6 libxinerama1 zlib1g libarchive-dev libavcodec-dev libavformat-dev libavresample-dev libavutil-dev libfontconfig-dev libfreetype6-dev libglu-dev libjpeg-turbo8-dev libopenal-dev libsfml-dev libswscale-dev libxinerama-dev
          make
